"""empty message

Revision ID: 816f049bc4a7
Revises: e2d8c7591581
Create Date: 2018-08-14 14:51:07.843472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816f049bc4a7'
down_revision = 'e2d8c7591581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
